### PR TITLE
update welcome email for new webmaker users

### PR DESCRIPTION
**Pull request by secretrobotron**

### CODE REVIEW

**Comment by secretrobotron** [comment]
@cadecairos R?

**Comment by secretrobotron** [comment]
@HPaulJohnson @thisandagain: take a look at the results? https://dl.dropboxusercontent.com/u/7054348/user_created.html

**Comment by cadecairos** [comment]
maybe change:
"Thank you for joining us to discover, create and share the Web" 

to:
"Thank you for joining us to discover, create, and share the Web"

**Comment by secretrobotron** [comment]
I'm not getting into arguments over oxford commas. @KevZawacki ?

**Comment by thisandagain** [comment]
As much as I love the oxford comma, I think our copy guidelines don't use them. 

R+

**Comment by cadecairos** [comment]
haha

**Comment by secretrobotron** [comment]
For future reference: https://www.mozilla.org/en-US/styleguide/communications/copy-rules/

**Comment by HPaulJohnson** [comment]
Not a deal breaker and not as fun as an oxford comma but it looks like the P.S. dropped off? After the signature this text should have been included: 

P.S.  Follow us on Twitter @webmaker for updates on the app and featured projects — and who knows, maybe your creation will be the next one we share with the world!

**Comment by secretrobotron** [comment]
Ah, good catch. I'll add.

**Comment by secretrobotron** [comment]
@HPaulJohnson better? https://dl.dropboxusercontent.com/u/7054348/user_created.html

**Comment by HPaulJohnson** [comment]
We should add a divider between PS and privacy policy to avoid confusion. I just sent you a sample text-only email as an example.

**Comment by secretrobotron** [comment]
@HPaulJohnson fixed. One more look?

**Comment by HPaulJohnson** [comment]
good to go

**Comment by secretrobotron** [comment]
Excellenté!

@cadecairos r?

**Comment by cadecairos** [comment]
I'm currently caring for an infant and can't use my laptop, can this wait till Monday or should we punt it to a West coaster for a look see

**Comment by secretrobotron** [comment]
@cadecairos take care of your child! I think this can wait until Monday. @thisandagain ?

**Comment by thisandagain** [comment]
R+

**Pull request merged**
