### PR TITLE
2016 Mozilla Festival Session Proposal email

### PR DESCRIPTION
**Pull request by cadecairos**
MozillaFoundation/mofo-devops#350

### CODE REVIEW

**Comment by cadecairos** [comment]
@edrushka does the copy look okay? 

mozfest2016-sessionproposal

**Comment by edrushka** [comment]
@cadecairos 

Can you please add links to the text
' MozFest 2016 program repo' --  https://github.com/MozillaFoundation/mozfest-program-2016
and
'this tutorial' --  https://www.pluralsight.com/blog/software-development/github-tutorial

**Comment by cadecairos** [comment]
@edrushka does the email subject look alright?

**Comment by edrushka** [comment]
@cadecairos Could you please change 'Mozilla Festival' to 'MozFest' in the subject line - thanks!

**Comment by cadecairos** [comment]
@ali r?

**Comment by alicoding** [comment]
R+

**Comment by mmmavis** [comment]
cc myself @mmmavis

**Pull request merged**
